Fix symmetric log uniform
bilby-dev/bilby pull request #848
Opened 2024-11-01 13:51 UTC by ColmTalbot

For a long time, some prior classes have cast inputs to numpy arrays this MR removes that behaviour and adds a test to make sure that sampling and evaluating the CDF do not cast to array.

This caused an error when evaluating the CDF many times and then combining the results.

I also streamlined some other behaviour in applying prior constraints that were originally flagged by @cjhaster.

I noticed that the Fermi-Dirac CDF hadn't been implemented for some reason so I added that and added to the CI test suite.
Finally, there was an issue with sampling from joint distributions where the results could be returned out of order.

Copied from https://git.ligo.org/lscsoft/bilby/-/merge_requests/1285

2025-01-13 13:47 UTC, mj-will commented on bilby/core/prior/analytical.py
> +            + 0.5 * (val >= -self.minimum) * (val <= self.minimum)
I think both statements here have changed from `>` to `>=`, is that intentional?

2025-01-23 15:09 UTC, mj-will commented on bilby/core/prior/analytical.py
> +            + 0.5 * (val >= -self.minimum) * (val <= self.minimum)
@ColmTalbot just bumping this

2025-02-04 14:29 UTC, mattpitkin commented
I've double checked the Fermi-Dirac prior CDF and it gives the correct expected result.

2025-02-04 15:56 UTC, mj-will reviewed
LGTM, I just have a couple of questions before I approve.

2025-02-04 15:56 UTC, mj-will commented on bilby/core/prior/slabspike.py
>          res = np.zeros(len(val))
Looking below these changes, there is some slightly janky logic relating to floats, do you think it's worth trying to fix this in this PR or shall we leave that for a future PR?

2025-02-04 15:56 UTC, mj-will commented on bilby/core/prior/dict.py
> +                result[key] = value
Could you help me understand what this loop is doing? I'm finding the logic of this part a bit hard to follow, it might benefit from a comment.

2025-02-04 16:04 UTC, mj-will commented on bilby/core/prior/slabspike.py
>          res = np.zeros(len(val))
Sure thing.

2025-02-06 16:27 UTC, asb5468 commented on bilby/core/prior/dict.py
> +                result[key] = value
+1

2025-02-06 16:45 UTC, asb5468 commented on test/core/prior/prior_test.py
> +                bilby.core.prior.JointPrior in prior.__class__.__mro__
Why is this test skipped for JointPriors with no finite upper bound?

2025-02-06 16:46 UTC, asb5468 requested changes
Left a few questions in the code. Wondering what github will do when I press "submit review" with "request changes" chosen.

2025-05-21 17:01 UTC, mj-will commented on bilby/core/prior/dict.py
> +                result[key] = value
Okay, I think I follow. Is this tested somewhere?

Either way, I think it would be useful to add a comment explaining this.

2025-08-21 14:25 UTC, closed without merging